### ISSUE TITLE
[Review] UI 코드 검토하기 

### ISSUE THREAD

**Issue by yuhaeun-la** [yuhaeun-la/LG_Flutter#3]

**Comment by modooJH** [comment]
# structure

[minor] ui밑에 views를 둔 이유가 있나요? depth만 깊어진것 같아요. 

[major]splash screen 적용하면 좋겠습니다. 

[minor] 굳이 안해도 될듯하지만, home/child_card.dart => home/widgets/child_card.dart로 구성하는것도 생각해볼 수 있겠습니다. 



# parent/home_view

-   [minor] Route적용 전이라서 HomeSquareButton 에 다음 페이지(destinationView)를 넘기신 것 같아요.  HomeSquareButton 생성하는 부분에서 바로  onPressed로 push 하면 어때요?

-   [minor] 최상위 stack이 없어도 될 것 같아요. 앞으로 개선을 위해 남겨둔 거라면 ok

-   [minor] column의 stretch는 없어도 됩니다. 

-   [major] HomeSquareButton size가 고정되어 있습니다.   screen size에 반응하도록 구성하는게 필요합니다.  이렇게 바꾸면 오른쪽 하단에 padding으로 위치 잡는 것도 안됩니다. Align이나 expanded를 활용할 수 있어요.  80px로 안 가는 이유는  spacer() 때문
![image-20240906184043014](https://github.com/user-attachments/assets/dd21cfbb-8fc9-4a55-9da2-d5e8d2590f4f)


-   [major] fontFamily도 colors_utils 처럼 const로 빼면 좋겠습니다. 
-   [minor]utils 밑에 color 나 assets 를 정의하는게 어색합니다. utils는 기능을 정의하는게 더 자연스럽게 느껴집니다.  
    styles, theme, constants 정도면 어떨까요? 

# EmergencyAlarmView&SoundListeningView

-   bottom 공백 40px 주는것은 좋지만 safeArea 내부에서 주면 좋겠어요.  MediaQuery.of(context).padding.bottom 값을 이용할 수도 있습니다. 
-   spacer, sizedbox 등을 이용해 여백을 조정했습니다.  이렇게 해도 괜찮지만, 이왕이면 단순하고 직관적이면 좋습니다. Column과 Expanded의 조합으로 표현가능합니다.
`SafeArea(
        child: Column(
          
          children: [
            Expanded(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  GestureDetector(
                    onTap: toggleAlarm, // 종 울림 상태 전환
                    child: AnimatedBuilder(
                      animation: _controller,
                      builder: (context, child) {
                        return Transform.rotate(
                          angle: isRinging ? _rotationAnimation.value : 0, // 아이콘 흔들림
                          child: Container(
                            decoration: BoxDecoration(
                              color: Colors.white, // 색상 애니메이션 적용 (흰색 -> 빨간색)
                              shape: BoxShape.circle,
                            ),
                            padding: EdgeInsets.all(40.0),
                            child: Icon(
                              isRinging ? Icons.notifications_active : Icons.notifications_off, // 아이콘 변경
                              size: 50.0,
                              color: isRinging ? _colorAnimation.value : pointColor, // 아이콘 색상
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                  SizedBox(height: 20.0),
                  Text(
                    isRinging ? '종이 울리고 있습니다' : '종을 울립니다',
                    style: TextStyle(
                      fontSize: 15.0,
                      fontFamily: 'NanumSquareNeo',
                      color: isRinging ? Colors.red : pointColor2,
                    ),
                  ),
                ],
              ),
            ),
            Align(
              alignment: Alignment.bottomRight,
              child: Image.asset(
                'assets/ballbaby.png',
                height: 150.0,
              ),
            )
          ],
        ),
      ),`




# 기타
WideToggelButton -> camel case 오타
